### ISSUE TITLE
Dealer Locator not working in exports markets

### ISSUE THREAD

**Issue by santi-homps** [aemsites/vg-macktrucks-com#10]
### Issue Type

None

### Summary

Dealers are not loading in some markets

### Priority

Blocker

### Description

After Helix-5 upgrade the country specific repositories have been replaced with a central one (vg-macktrucks-com) so the dealer locator needs to be upgraded to the V2 version of it in order to identify the correct markets:

Markets where this already been implemented:
- [x] New Zealand
- [x] Colombia
- [x] Mexico
- [x] US
- [x] Canada

The rest will have to be updated when moving to Helix-5 architecture.

### Affected Device Classes

Mobile, Tablet, Desktop

**Comment by bouchriy** [comment]
This issue has been migrated to Azure DevOps: https://dev.azure.com/volvo-digital-experience/DEX Platform/_workitems/edit/132049
