### ISSUE TITLE
Bug: News Feed Not Working for Export Markets

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/vg-macktrucks-com#104]
### Issue Type

Bug

### Priority

Blocker

### Description

The News Feed for a few export markets is not functioning as expected. When accessing the feed URL for specific markets, no data is returned or an error occurs.

### Affected Device Classes

Tablet, Mobile, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices 

### Steps to Reproduce

1. Open: https://main--macktrucks-com-do--volvogroup.aem.live/body-builder-news.json
2. Observe the issue (no data or error message displayed).
3. The feed is expected to return a JSON response with news data but does not.

### Expected Results

The news feed should return a valid JSON response with relevant news data for export markets.

### Actual Results

The URL does not return the expected JSON data. The News Feed appears broken or inaccessible for specific export markets.

### Attachment

![Image](https://github.com/user-attachments/assets/1b50a988-9440-46c8-90c2-3e3b17e483e0)

**Comment by BeckyMedlin** [comment]
@Kannan-CM Is this all export markets or only a few? Please specify the markets. Thank you!

**Comment by alexiscoelho** [comment]
Another issue is that the `news-list` grabs an hardcoded link for the xml file and that needs to come as a property on the component.

**Comment by jonatan-lledo-netcentric** [comment]
the json file is empty, even if is already previewed/published, if is empty, the result JSON it's ok if it has 0 results

**Comment by verareljic** [comment]
Waiting for meeting with Darin on 12/9/2024 FYI @BeckyMedlin @ZoeBeykirch @KJohnsn

**Comment by VladMano** [comment]
Testing Completed. Everything works accordingly.
