### ISSUE TITLE
Bug: The V2 Category Collage block is broken

### ISSUE THREAD

**Issue by amglebihan** [aemsites/vg-macktrucks-com#13]
### Issue Type

None

### Priority

None

### Description

The V2 Category Collage block looks broken.

### Steps to Reproduce

1. Navigate to https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-category-collage
2. Observe the block.

### Expected Results

The block should look and work as expected.

### Actual Results

The block’s design appears broken.

**Comment by BeckyMedlin** [comment]
Need to ensure this block is included in the Sidekick Library.

**Comment by amglebihan** [comment]
@BeckyMedlin It's already in the Sidekick library, it's the page linked in the "steps to reproduce" section.
