### ISSUE TITLE
Bug: The V2 Media With Content block has formatting issues

### ISSUE THREAD

**Issue by amglebihan** [aemsites/vg-macktrucks-com#14]
### Issue Type

Bug

### Priority

None

### Description

In the V2 Media With Content block, dashes are appearing next to the bullet points, and "null" is showing up in some areas.

### Steps to Reproduce

1. Navigate to https://main--vg-macktrucks-com--volvogroup.aem.live/block-library/blocks/v2-media-with-content and https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/zoe/block-test (at the bottom of the page).
2. Observe the block.

### Expected Results

No dashes should appear next to the bullet points, and "null" should not be displayed.

### Actual Results

1. Dashes are appearing next to the bullet points.  
2. "Null" is showing up in some areas.
![Image](https://github.com/user-attachments/assets/24b64e84-a8c6-4ef5-a207-884d1a1acfcf)
![Image](https://github.com/user-attachments/assets/b084ee46-0c99-477d-a38e-3c928e4c66b2)
![image](https://github.com/user-attachments/assets/32730788-5f6d-410a-bca3-4c817cd03c91)

**Comment by silviulungu** [comment]
Testing completed. Everything works accordingly!
