### ISSUE TITLE
Bug: Redesign sub-nav is no longer working on production

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/vg-macktrucks-com#147]
### Issue Type

Bug

### Summary

Sub-Nav is no longer working, not being displayed on the websites on any page it is used on. 

### Priority

Blocker

### Description

The new sub navigation, which displays under the hero section with a button, is not working on the redesign pages of the main website. It was functioning correctly yesterday but is no longer visible or interactive today.

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices 

### Steps to Reproduce

1. Navigate to a page that uses redesign sub-nav (there are many, here are a few examples): 
 - https://www.macktrucks.com/live-tour/
 - https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/pere/brand-identity-guidelines/graphic-elements
 - https://www.macktrucks.com/trucks/anthem/
2. Observe how the sub-nav is no longer displayed on the page

### Expected Results

Figma for reference of what was developed: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=auto&node-id=2243-155090
![Image](https://github.com/user-attachments/assets/e4db8231-f5dc-4702-bd23-3b7cad503008)
![Image](https://github.com/user-attachments/assets/6a6302fb-4a79-4f48-a70c-e60f9d483e41)

### Actual Results

Sub-nav is missing and no longer displaying

**Comment by silviulungu** [comment]
Testing completed. Everything works accordingly!
