### ISSUE TITLE
Bug: The V2 Magazine Tabbed Carousel has design issues

### ISSUE THREAD

**Issue by amglebihan** [aemsites/vg-macktrucks-com#15]
### Issue Type

Bug

### Priority

None

### Description

A bullet point appears next to the first slide of the V2 Magazine Tabbed Carousel, and the controls are misaligned.

### Steps to Reproduce

1. Navigate to https://main--vg-macktrucks-com--volvogroup.aem.live/block-library/blocks/v2-magazine-tabbed-carousel
2. Observe the block.

### Expected Results

1. No bullet point should appear next to the first slide.  
2. The controls should be properly aligned within the block.

### Actual Results

1. A bullet point appears next to the first slide.
2. The controls aren't properly aligned within the block.

<img width="572" alt="Screenshot 2024-11-04 at 12 20 54" src="https://github.com/user-attachments/assets/61e3cd23-db09-44b1-8e0b-6838924925cc">
<img width="1298" alt="Screenshot 2024-11-04 at 12 21 17" src="https://github.com/user-attachments/assets/79ea6b72-2664-42ad-afaf-61057891b5f2">

**Comment by silviulungu** [comment]
Testing completed. Everything works accordingly.
