### ISSUE TITLE
Bug: V2 Navigation Hub, bullet points shouldn't appear in the block

### ISSUE THREAD

**Issue by amglebihan** [aemsites/vg-macktrucks-com#16]
### Issue Type

None

### Priority

None

### Description

Unnecessary bullet points are appearing in the block.

### Steps to Reproduce

1. Navigate to https://main--vg-macktrucks-com--volvogroup.aem.live/block-library/blocks/v2-navigation-hub
2. Observe the block.

### Expected Results

No bullet points should be displayed in the block.

### Actual Results

Bullet points are displayed in the block.![Image](https://github.com/user-attachments/assets/81743db8-4d73-480a-8c47-49b17a201eff)

**Comment by VladMano** [comment]
Testing completed. The bullet points no longer show up inside the block.
