### ISSUE TITLE
Bug: Issues with [v2 cards (no background, 2 cards row)]

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/vg-macktrucks-com#17]
### Issue Type

Bug

### Summary

There are two issues with this variant of the v2 cards block.  Issue 1: odd superscript spacing in link  Issue 2: lists have both bullets and dashes

### Priority

High

### Description

There are two specific issues with this variant of the v2 cards (no background, 2 cards row) block that need to be addressed.

- Issue 1: Odd Superscript Spacing in Link. The spacing in the superscript within links appears irregular, breaking from the expected designs. 

- Issue 2: Lists Displaying Both Bullets and Dashes. The lists in this variant are showing both bullet points and dashes. There should only bullet points displayed. 

Related to https://github.com/aemsites/vg-macktrucks-com/issues/19 

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All browsers and devices. 

### Steps to Reproduce

1. Navigate to: main--vg-macktrucks-com--hlxsites.hlx.page/drafts/wendy.kruger/bugs#v2-cards:~:text=Issues,-with%20v2%20cards
2. Observe the issues with block described above. 

### Actual Results

![image](https://github.com/user-attachments/assets/17ed62cb-36bb-44e6-8bd5-4a0e7855fe66)
![image](https://github.com/user-attachments/assets/90cc4422-461b-4530-83a9-6396df4f5640)
![image](https://github.com/user-attachments/assets/8979a79d-1daa-4b88-91e2-5fc1448803eb)

**Comment by VladMano** [comment]
Testing completed. Everything works accordingly.

**Comment by bouchriy** [comment]
This issue has been migrated to Azure DevOps: https://dev.azure.com/volvo-digital-experience/DEX Platform/_workitems/edit/132212
