### ISSUE TITLE
Bug: V2 Columns,  bullet points are displayed alongside dashes and the padding is off in some places

### ISSUE THREAD

**Issue by amglebihan** [aemsites/vg-macktrucks-com#19]
### Issue Type

None

### Priority

None

### Steps to Reproduce

1. Navigate to https://main--vg-macktrucks-com--volvogroup.aem.page/block-library/blocks/v2-columns
2. Observe the block's list items.

### Expected Results

1. Columns (with-background-image): bullet points should not appear next to dashes. The left padding should be correct.
2. Columns (with-background-image, icon-list): the left padding should be correct.
3. Columns (with-background-image, navigation-links): the left padding should be correct.

### Actual Results

1. Columns (with-background-image): bullet points are displayed alongside dashes, and the left padding of the list items is set too far to the right.
2. Columns (with-background-image, icon-list): the left padding of the list items is set too far to the right.
3. Columns (with-background-image, navigation-links): the left padding of the list items is set too far to the right.
![Image](https://github.com/user-attachments/assets/68f3b223-24cc-42ee-a042-d392096bfec5)
![Image](https://github.com/user-attachments/assets/2e5e6b80-3599-402f-b81e-876c044152f1)
![Image](https://github.com/user-attachments/assets/add21e7d-7877-45ac-8d93-161f4d1237b5)

**Comment by silviulungu** [comment]
Testing completed. Everything works accordingly.
