### ISSUE TITLE
Defect:  MX :  Pre-footer section on macktrucks.com.mx takes user to old configurator

### ISSUE THREAD

**Issue by girishdigrajkar** [aemsites/vg-macktrucks-com#20]
### Issue Type

Defect

Pre-footer section on macktrucks.com.mx takes user to old configurator 

_No response_

### Priority

High

### Description

Pre-footer section on macktrucks.com.mx takes user to old configurator so content need to be adjusted accordingly for all live sites post helix5 migration i.e. 

https://www.macktrucks.ca/
https://www.macktrucks.com.mx/
https://www.macktrucks.co.nz/
https://www.macktrucks.com.co/

### Steps to Reproduce

1. Navigate to **https://www.macktrucks.com.mx/**
2. Scroll down to pre footer section and click on 'Construye tu camión' link
3. Verify the page opened

### Expected Results

1. It should take user to new MX configurator

### Actual Results

1. It takes user to old .com configurator

**Comment by BeckyMedlin** [comment]
@girishdigrajkar Is this still a problem? Please verify and advise. Thank you!

**Comment by girishdigrajkar** [comment]
Hi @BeckyMedlin , @Kannan-CM,
Validated and please see latest status , content needs to be fixed: 

https://www.macktrucks.ca/  :           Both pre footer link and  'main menu > Trucks> Anthem > Build yours' takes user to old configurator 'https://www.macktrucks.com/trucks/build/'  : FAILED
https://www.macktrucks.com.mx/ :   Content issue is fixed now : PASSED
https://www.macktrucks.co.nz/     :   No 'Main Menu > Trucks> Build yours' / pre footer  'Build My Mack' links observed: FAILED
https://www.macktrucks.com.co/ :     Content issue is fixed now : PASSED

**Comment by Varunvolvo** [comment]
The footer link for macktrucks.ca is updated with the new configurator link. 
We do not have configurator for NZ, so that can be ignored.

**Comment by BeckyMedlin** [comment]
@girishdigrajkar Please re-verify per @Varunvolvo's update. Thank you!

**Comment by girishdigrajkar** [comment]
Hi @Varunvolvo :  CA issues are still observed as Menu links shows blank page and pre footer link shows old configurator: 

![image](https://github.com/user-attachments/assets/4831e548-5882-438c-a87e-8dda8036e8a9)

**Comment by girishdigrajkar** [comment]
Pages were republished by @Varunvolvo so marking this bug to 'In Testing' now;

**Comment by girishdigrajkar** [comment]
Validated and able to get the correct results and hence, marking this bug to Testing completed status.
