### ISSUE TITLE
NFR: Remove sections around content fragments to be loaded in the Accordions

### ISSUE THREAD

**Issue by alexiscoelho** [aemsites/vg-macktrucks-com#28]
### Context/Description

As a User I would like to not have the extra space left after the Accordion component until the next component:

<img width="1371" alt="Screenshot 2024-11-15 at 12 31 11" src="https://github.com/user-attachments/assets/f6bbbc4e-834f-4470-b6f0-dcb7361e9c0a">

### Acceptance Criteria

**User AC:**
Remove the sections around the fragments/tables:

**Identified pages with the problem pages:**

- [x] https://main--macktrucks-sv--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] https://main--macktrucks-sv--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] https://main--macktrucks-sv--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] https://main--macktrucks-hn--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] https://main--macktrucks-hn--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] https://main--macktrucks-hn--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] https://main--macktrucks-gt--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] https://main--macktrucks-gt--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] https://main--macktrucks-com-ec--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] https://main--macktrucks-com-ec--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] https://main--macktrucks-cl--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] https://main--macktrucks-cl--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] https://main--macktrucks-cl--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] https://main--macktrucks-com-bo--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] https://main--macktrucks-com-bo--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] https://main--macktrucks-com-bo--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] https://main--macktrucks-com-ar--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive-hd/
- [x] https://main--macktrucks-com-ar--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/
- [x] https://main--macktrucks-com-ar--volvogroup.aem.live/powertrain-and-suspensions/engines/mp8/
- [x] https://main--macktrucks-com-au--volvogroup.aem.live/powertrain-and-suspensions/transmissions/mdrive/

<img width="841" alt="Screenshot 2024-11-15 at 12 37 10" src="https://github.com/user-attachments/assets/b1e17a5c-9439-4987-b3d9-2e0fa0ddb4f4">
<img width="808" alt="Screenshot 2024-11-15 at 12 36 38" src="https://github.com/user-attachments/assets/da9ea80a-cfac-431a-abb7-2e89afd9a5f5">

**Comment by Kannan-CM** [comment]
Hi @alexiscoelho ,

@Varunvolvo has completed this
