### ISSUE TITLE
Mack Trucks NZ Website security vulnerabilities

### ISSUE THREAD

**Issue by KJohnsn** [aemsites/vg-macktrucks-com#32]
### Issue Type

Defect

### Summary

Security issues raised by the NZ team for the Mack Trucks NZ site

### Priority

Critical

### Description

The Mack Trucks NZ security team conducted a website vulnerability scan and they found some level 3 and level 4. The attached spreadsheet provides a list of the vulnerabilities which need to be addressed urgently.

![Mack Trucks NZ security issues snapshot](https://github.com/user-attachments/assets/58b23a6f-be1a-46fb-9cc2-2620db498eeb)

### Affected Device Classes

Mobile, Tablet, Desktop

### Affected Browsers/Devices and Versions

All current versions of major browsers: Chrome, Edge, Firefox, Safari

### Steps to Reproduce

Run a security scan on Mack Trucks NZ
Review the analysis

### Expected Results

No security issues found

### Actual Results

Several security issues found which need to be addressed and rescanned to ensure that the issues have been resolved.

### Attachment

[Scan_Report_macktrucks.co.nz.xlsx](https://github.com/user-attachments/files/17836520/Scan_Report_macktrucks.co.nz.xlsx)

**Comment by BeckyMedlin** [comment]
MT NZ DAST scan results reveal only low-level vulnerabilities. Closing this ticket and will share results with Roberto Vega, @dkuntze , and @alexiscoelho. Closing this ticket as the scan reported initially was not authorized by Volvo Group.

**Comment by bouchriy** [comment]
This issue has been migrated to Azure DevOps: https://dev.azure.com/volvo-digital-experience/DEX Platform/_workitems/edit/132052
