### ISSUE TITLE
V2 Collage/Carousel blocks are broken

### ISSUE THREAD

**Issue by BeckyMedlin** [aemsites/vg-macktrucks-com#33]
### Issue Type

Bug

### Summary

V2 collage/carousel blocks are not working as designed

### Priority

Blocker

### Description

Reported by @WendyKruger: 
Three collage/carousel blocks are broken (note: two of the three are not in the sidekick library):
1. v2 stories carousel https://main--vg-macktrucks-com--hlxsites.hlx.page/block-library/blocks/v2-stories-carousel

2. v2 image collage https://main--vg-macktrucks-com--hlxsites.hlx.page/block-library/blocks/v2-image-collage

3. v2 category collage https://main--vg-macktrucks-com--hlxsites.hlx.live/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-category-collage&index=0    (See related issue #13 )

You can see all these on this page: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/wendy.kruger/magazine/bulldog-article-title-length-exploration

### Affected Device Classes

Desktop, Tablet, Mobile

### Affected Browsers/Devices and Versions

Chrome

### Steps to Reproduce

Navigate to page -- see examples here: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/wendy.kruger/magazine/bulldog-article-title-length-exploration

### Expected Results

Blocks are not displaying as designed.

### Actual Results

See examples

**Comment by BeckyMedlin** [comment]
@girishdigrajkar Please verify issues -- do these need to be separate issues?

**Comment by girishdigrajkar** [comment]
Validated and seems the root cause is that code is referring old sidekick whereas, it should refer to new infra sidekick library.
Root cause is simillar so, ok to have one fix for all above sub issue.

**Comment by alexiscoelho** [comment]
The `v2-image-collage` component doesn't exist. I will delete that library page

**Comment by silviulungu** [comment]
Testing completed.

1. V2 Stories Carousel is working fine on the [AEM](https://main--vg-macktrucks-com--volvogroup.aem.page/drafts/wendy.kruger/magazine/bulldog-article-title-length-exploration) page.
2. V2 Image Collage component does not exist and the page has been deleted.
3. V2 Category Collage is present on the Develop branch in the [Sidekick Library](https://develop--vg-macktrucks-com--volvogroup.aem.page/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-category-collage&index=0) and is working as expected. The component will be pushed on Main branch at the right time.
