### ISSUE TITLE
Bug: Add failsafe code when ACC_ENG_TRACKING is missing from the constants config

### ISSUE THREAD

**Issue by alexiscoelho** [aemsites/vg-macktrucks-com#36]
### Issue Type

None

### Priority

None

### Description

Add failsafe code when ACC_ENG_TRACKING is missing from the constants config so that pages where the config is not needed don't break if we remove the configuration entirely.

### Steps to Reproduce

When ACC_ENG_TRACKING is missing the page will be broken.

### Expected Results

- [ ] The code doesn't break if the value is not present on the constants file
- [ ] On the method `extractObjectFromArray` add a failsafe code to ensure that `data` is iterable  
- [ ] On the method `formatStringToArray` add a failsafe code to ensure that `inputString` is a string (and not undefined)  
- [ ] On the file `/scripts/validate-elements.js` ensure the code doens't break when `TOOLS_CONFIGS` is not set on the constants file
- [ ] Remove all occurrences in all markets where the config is set but empty so the code doesn't break

### Actual Results

The code breaks when the configuration is not present on the constants file

**Comment by BeckyMedlin** [comment]
@mollyaljenkins @alexiscoelho  We need a user story for this ticket, please. Thank you!

**Comment by girishdigrajkar** [comment]
Validated this issue with help of dev  and the PR URL works fine without showing any error on console both in case  ACC_ENG_TRACKING parameter is present / omitted from constants.json 

This confirms the failsafe code in place for ACC_ENG_TRACKING parameter hence, this ticket could proceed to closing.

**Comment by bouchriy** [comment]
This issue has been migrated to Azure DevOps: https://dev.azure.com/volvo-digital-experience/DEX Platform/_workitems/edit/132224
