### ISSUE TITLE
Bug: Modal Carousel Not Displaying All Hotspot Cards

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/vg-macktrucks-com#43]
### Issue Type

Bug

### Summary

One of the hotspot modals is not showing when paging through the cards

### Priority

High

### Description

Modal carousel only displays three out of four hotspot cards when a user navigates through the carousel using the arrows. The fourth card is only accessible by clicking on it directly, when it should be visible when the user scrolls through the carousel.

### Affected Device Classes

Mobile, Tablet, Desktop

### Out of Scope

- [x] Block enhancement to have no hotspot limit

### Affected Browsers/Devices and Versions

Tested on Windows and MacBook desktop on browser Chrome and Edge. 

### Steps to Reproduce

1. Navigate to: https://main--vg-macktrucks-com--volvogroup.aem.live/ https://main--vg-macktrucks-com--hlxsites.hlx.page/powertrain-and-suspensions/engines/mp8/ (only view the pre-production and not published page, as we will not publish it until this is resolved)
2. Click on one of the hotspots on the engine.
3. Use the arrows to navigate through the hotspot cards.
4. Observe how only 3 out of the 4 cards are visible when clicking through. 
 

https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/wendy.kruger/bugs#hotspot-modal-issues

### Expected Results

All hotspot cards should be accessible when paging through the carousel using the navigation arrows.

### Actual Results

View the video of the user experience here: https://main--vg-macktrucks-com--hlxsites.hlx.page/drafts/wendy.kruger/bugs#hotspot-modal-issues

**Comment by amglebihan** [comment]
I’ve removed a hardcoded value that was limiting the modal carousel’s controls to navigating only between three slides maximum. The carousel will now function correctly with any number of slides.

**Comment by AsmitKMishra** [comment]
Testing Completed. Modal carousel now now shows all cards and works as expected.
