### ISSUE TITLE
FR: [V2 Resources – Dotted background] Magazine Variant

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/vg-macktrucks-com#60]
### Context/Description

As a Mack Trucks Bulldog magazine editor, I want a new variant of the existing [V2 Resources – Dotted Background] block, so that I can display a call to action encouraging readers to subscribe, with a visually appealing design that drives more engagement.

### Acceptance Criteria

**Editor AC:**
- [x] I can use this block on any page. 
- [x] I can find this block in the AEM Sidekick Library. 
- [x] I can edit all of the text on this block. 
- [x] I can configure the button link. 

**Non-functional AC:**
- [x] Features H2 text over a dotted background. On desktop this is displayed on the left side of the block, and on mobile this is displayed at the top of the block. 
- [x] Features body text displayed to the right of the H2 text on desktop, and underneath the H2 text on mobile. 
- [x] Gold button is displayed underneath the body text that links to a page, currently the button exists as a link
- [x] Design follows the below Figma layout. 
- [x] Block will be named V2 Resources - Magazine 
- [x] The dotted background already exists as part of the section metadata

### Note

The  [V2 Resources – Dotted background] block is very close and should be tweaked for the magazine variant design 
https://main--vg-macktrucks-com--hlxsites.hlx.live/tools/sidekick/library.html?plugin=blocks&path=/block-library/blocks/v2-resources&index=1

### Attachment / link to Figma

Desktop: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=11294-44521&m=dev

![Image](https://github.com/user-attachments/assets/b1ad772f-43b9-45ae-a6e5-e2f2c9ca45b3)

Mobile: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=11294-44638&m=dev

![Image](https://github.com/user-attachments/assets/614ba0ef-5313-47e5-924e-023dc71d9008)

**Comment by VladMano** [comment]
Testing completed. Everyhing works accordingly.
