### ISSUE TITLE
FR: Magazine Article layout

### ISSUE THREAD

**Issue by ZoeBeykirch** [aemsites/vg-macktrucks-com#71]
### Context/Description

As a Mack Trucks content author, I want to adjust the Magazine template spacing. Since the site is responsive it will adjust dynamically with the viewport size. In this ticket we will focus on content max-width and address vertical spacing in another ticket.

### Acceptance Criteria

**User AC:**
- [ ] As a website user, when I read a Bulldog Magazine article on my desktop computer, I see the body of text has more white space on the left and right. 

**Non-functional AC:**
- [ ] The spacing change will be done in the aemsites/vg-macktrucks-com#88 
- [ ] All blocks will have a max width of 1040px 
- [ ] Article text and pull quote of 690px 
- [ ] Subhead, Attribution, Social block of 864px 

### Attachment / link to Figma

Desktop: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=14119-2389

![Image](https://github.com/aemsites/vg-macktrucks-com/assets/125895595/ee198e7e-39a4-4721-a565-647f9aecfd56)

Mobile: https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?m=dev&node-id=2222-52896

![Image](https://github.com/aemsites/vg-macktrucks-com/assets/125895595/766edfdb-ba2c-464c-b95a-b2249b3b2d5f)

**Comment by ZoeBeykirch** [comment]
@WendyKruger  Hi. Alan is finalizing the styling for the Bulldog magazine article template and have a few remaining questions about the article's headline. The original AC stated that it should be an H1, but:
- If the Magazine Hero has a title defined, that title is set as an H1. Since there shouldn't be two H1 elements on the same page, the article's headline should then be an H2.
- If the Magazine Hero does not have a title defined, the article's headline can be set as an H1.
We need clarification on how the article's headline should be styled when it is an H1 or H2. While the project has globally defined styles for each type of headline, the [design in Figma](https://www.figma.com/design/oNwe2jHIICPMIe551EY62l/Mack-Reskin---Full-Project?node-id=2222-51364&m=dev) uses the styling of an H3 for the article's headline. Should I apply the default styles for H1 and H2 instead? If I follow the default styles, the title will appear larger than it does in the current designs. How should I proceed?

**Comment by bouchriy** [comment]
This issue has been migrated to Azure DevOps: https://dev.azure.com/volvo-digital-experience/DEX Platform/_workitems/edit/131965
